//go:build sweep
// +build sweep

package sweep_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/accessanalyzer"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/acm"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/acmpca"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/amplify"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/apigateway"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/apigatewayv2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/appconfig"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/appmesh"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/apprunner"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/appstream"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/appsync"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/autoscaling"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/autoscalingplans"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/backup"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/batch"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/budgets"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloud9"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudformation"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudfront"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudhsmv2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudsearch"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudtrail"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudwatch"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cloudwatchlogs"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/codeartifact"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/codebuild"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/codedeploy"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/codepipeline"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cognitoidp"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/configservice"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/connect"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/cur"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/datasync"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/dax"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/directconnect"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/dlm"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/dms"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ds"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/dynamodb"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ec2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ecr"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ecrpublic"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ecs"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/efs"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/eks"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/elasticache"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/elasticbeanstalk"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/elasticsearch"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/elb"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/elbv2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/emr"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/events"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/firehose"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/fsx"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/gamelift"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/glacier"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/globalaccelerator"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/glue"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/guardduty"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/iam"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/imagebuilder"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/iot"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kafka"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kafkaconnect"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/keyspaces"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kinesis"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kinesisanalytics"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kinesisanalyticsv2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/kms"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/lambda"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/lexmodels"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/licensemanager"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/lightsail"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/memorydb"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/mq"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/mwaa"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/neptune"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/networkfirewall"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/networkmanager"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/opsworks"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/pinpoint"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/qldb"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/quicksight"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/rds"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/redshift"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/route53"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/route53recoverycontrolconfig"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/route53resolver"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/s3"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/s3control"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/sagemaker"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/schemas"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/secretsmanager"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/servicecatalog"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/servicediscovery"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ses"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/sns"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/sqs"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ssm"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/ssoadmin"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/storagegateway"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/synthetics"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/timestreamwrite"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/transfer"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/waf"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/wafregional"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/wafv2"
	_ "github.com/PixarV/terraform-provider-ritt/internal/service/workspaces"
	"github.com/PixarV/terraform-provider-ritt/internal/sweep"
)

func TestMain(m *testing.M) {
	sweep.SweeperClients = make(map[string]interface{})
	resource.TestMain(m)
}
